version: '3.3'

networks:
  backend:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    command: yarn ${NODE_ENV}
    restart: on-failure
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend
